# Generated by Django 5.0.3 on 2024-03-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
